### ISSUE TITLE
"Illegal format!": Plugin does not work with new CTC-Version (Version 8.0)

### ISSUE THREAD

**Issue by Robert-Ilg** [Londran/sonar-ctc#5]
When parsing the ctc-results an error occurs  "Illegal format!".

The error is due to changes in the profile.txt layout. The new version seems to introduce a new line "Headers extracted  : 0" in the summery at the end of the file. The pattern "REPORT_FOOTER" does not count with that line and therefore cannot find the summery at all.

Note that the solution should work with new and old versions.

**Comment by Londran** [comment]
Is fixed.
